SQLITE_VERSION                        := "3.43.2"
SQLITE_VERSION_NUMBER                 := 3043002
SQLITE_SOURCE_ID                      := "2023-10-10 12:14:04 4310099cce5a487035fa535dd3002c59ac7f1d1bec68d7cf317fd3e769484790"
SQLITE_OK                             := 0                          ; Successful result
SQLITE_ERROR                          := 1                          ; Generic error
SQLITE_INTERNAL                       := 2                          ; Internal logic error in SQLite
SQLITE_PERM                           := 3                          ; Access permission denied
SQLITE_ABORT                          := 4                          ; Callback routine requested an abort
SQLITE_BUSY                           := 5                          ; The database file is locked
SQLITE_LOCKED                         := 6                          ; A table in the database is locked
SQLITE_NOMEM                          := 7                          ; A malloc() failed
SQLITE_READONLY                       := 8                          ; Attempt to write a readonly database
SQLITE_INTERRUPT                      := 9                          ; Operation terminated by sqlite3_interrupt(
SQLITE_IOERR                          := 10                         ; Some kind of disk I/O error occurred
SQLITE_CORRUPT                        := 11                         ; The database disk image is malformed
SQLITE_NOTFOUND                       := 12                         ; Unknown opcode in sqlite3_file_control()
SQLITE_FULL                           := 13                         ; Insertion failed because database is full
SQLITE_CANTOPEN                       := 14                         ; Unable to open the database file
SQLITE_PROTOCOL                       := 15                         ; Database lock protocol error
SQLITE_EMPTY                          := 16                         ; Internal use only
SQLITE_SCHEMA                         := 17                         ; The database schema changed
SQLITE_TOOBIG                         := 18                         ; String or BLOB exceeds size limit
SQLITE_CONSTRAINT                     := 19                         ; Abort due to constraint violation
SQLITE_MISMATCH                       := 20                         ; Data type mismatch
SQLITE_MISUSE                         := 21                         ; Library used incorrectly
SQLITE_NOLFS                          := 22                         ; Uses OS features not supported on host
SQLITE_AUTH                           := 23                         ; Authorization denied
SQLITE_FORMAT                         := 24                         ; Not used
SQLITE_RANGE                          := 25                         ; 2nd parameter to sqlite3_bind out of range
SQLITE_NOTADB                         := 26                         ; File opened that is not a database file
SQLITE_NOTICE                         := 27                         ; Notifications from sqlite3_log()
SQLITE_WARNING                        := 28                         ; Warnings from sqlite3_log()
SQLITE_ROW                            := 100                        ; sqlite3_step() has another row ready
SQLITE_DONE                           := 101                        ; sqlite3_step() has finished executing
SQLITE_ERROR_MISSING_COLLSEQ          := (SQLITE_ERROR      | (1<<8))
SQLITE_ERROR_RETRY                    := (SQLITE_ERROR      | (2<<8))
SQLITE_ERROR_SNAPSHOT                 := (SQLITE_ERROR      | (3<<8))
SQLITE_IOERR_READ                     := (SQLITE_IOERR      | (1<<8))
SQLITE_IOERR_SHORT_READ               := (SQLITE_IOERR      | (2<<8))
SQLITE_IOERR_WRITE                    := (SQLITE_IOERR      | (3<<8))
SQLITE_IOERR_FSYNC                    := (SQLITE_IOERR      | (4<<8))
SQLITE_IOERR_DIR_FSYNC                := (SQLITE_IOERR      | (5<<8))
SQLITE_IOERR_TRUNCATE                 := (SQLITE_IOERR      | (6<<8))
SQLITE_IOERR_FSTAT                    := (SQLITE_IOERR      | (7<<8))
SQLITE_IOERR_UNLOCK                   := (SQLITE_IOERR      | (8<<8))
SQLITE_IOERR_RDLOCK                   := (SQLITE_IOERR      | (9<<8))
SQLITE_IOERR_DELETE                   := (SQLITE_IOERR      | (10<<8))
SQLITE_IOERR_BLOCKED                  := (SQLITE_IOERR      | (11<<8))
SQLITE_IOERR_NOMEM                    := (SQLITE_IOERR      | (12<<8))
SQLITE_IOERR_ACCESS                   := (SQLITE_IOERR      | (13<<8))
SQLITE_IOERR_CHECKRESERVEDLOCK        := (SQLITE_IOERR      | (14<<8))
SQLITE_IOERR_LOCK                     := (SQLITE_IOERR      | (15<<8))
SQLITE_IOERR_CLOSE                    := (SQLITE_IOERR      | (16<<8))
SQLITE_IOERR_DIR_CLOSE                := (SQLITE_IOERR      | (17<<8))
SQLITE_IOERR_SHMOPEN                  := (SQLITE_IOERR      | (18<<8))
SQLITE_IOERR_SHMSIZE                  := (SQLITE_IOERR      | (19<<8))
SQLITE_IOERR_SHMLOCK                  := (SQLITE_IOERR      | (20<<8))
SQLITE_IOERR_SHMMAP                   := (SQLITE_IOERR      | (21<<8))
SQLITE_IOERR_SEEK                     := (SQLITE_IOERR      | (22<<8))
SQLITE_IOERR_DELETE_NOENT             := (SQLITE_IOERR      | (23<<8))
SQLITE_IOERR_MMAP                     := (SQLITE_IOERR      | (24<<8))
SQLITE_IOERR_GETTEMPPATH              := (SQLITE_IOERR      | (25<<8))
SQLITE_IOERR_CONVPATH                 := (SQLITE_IOERR      | (26<<8))
SQLITE_IOERR_VNODE                    := (SQLITE_IOERR      | (27<<8))
SQLITE_IOERR_AUTH                     := (SQLITE_IOERR      | (28<<8))
SQLITE_IOERR_BEGIN_ATOMIC             := (SQLITE_IOERR      | (29<<8))
SQLITE_IOERR_COMMIT_ATOMIC            := (SQLITE_IOERR      | (30<<8))
SQLITE_IOERR_ROLLBACK_ATOMIC          := (SQLITE_IOERR      | (31<<8))
SQLITE_IOERR_DATA                     := (SQLITE_IOERR      | (32<<8))
SQLITE_IOERR_CORRUPTFS                := (SQLITE_IOERR      | (33<<8))
SQLITE_IOERR_IN_PAGE                  := (SQLITE_IOERR      | (34<<8))
SQLITE_LOCKED_SHAREDCACHE             := (SQLITE_LOCKED     |  (1<<8))
SQLITE_LOCKED_VTAB                    := (SQLITE_LOCKED     |  (2<<8))
SQLITE_BUSY_RECOVERY                  := (SQLITE_BUSY       |  (1<<8))
SQLITE_BUSY_SNAPSHOT                  := (SQLITE_BUSY       |  (2<<8))
SQLITE_BUSY_TIMEOUT                   := (SQLITE_BUSY       |  (3<<8))
SQLITE_CANTOPEN_NOTEMPDIR             := (SQLITE_CANTOPEN   | (1<<8))
SQLITE_CANTOPEN_ISDIR                 := (SQLITE_CANTOPEN   | (2<<8))
SQLITE_CANTOPEN_FULLPATH              := (SQLITE_CANTOPEN   | (3<<8))
SQLITE_CANTOPEN_CONVPATH              := (SQLITE_CANTOPEN   | (4<<8))
SQLITE_CANTOPEN_DIRTYWAL              := (SQLITE_CANTOPEN   | (5<<8)) ; Not Used
SQLITE_CANTOPEN_SYMLINK               := (SQLITE_CANTOPEN   | (6<<8))
SQLITE_CORRUPT_VTAB                   := (SQLITE_CORRUPT    | (1<<8))
SQLITE_CORRUPT_SEQUENCE               := (SQLITE_CORRUPT    | (2<<8))
SQLITE_CORRUPT_INDEX                  := (SQLITE_CORRUPT    | (3<<8))
SQLITE_READONLY_RECOVERY              := (SQLITE_READONLY   | (1<<8))
SQLITE_READONLY_CANTLOCK              := (SQLITE_READONLY   | (2<<8))
SQLITE_READONLY_ROLLBACK              := (SQLITE_READONLY   | (3<<8))
SQLITE_READONLY_DBMOVED               := (SQLITE_READONLY   | (4<<8))
SQLITE_READONLY_CANTINIT              := (SQLITE_READONLY   | (5<<8))
SQLITE_READONLY_DIRECTORY             := (SQLITE_READONLY   | (6<<8))
SQLITE_ABORT_ROLLBACK                 := (SQLITE_ABORT      | (2<<8))
SQLITE_CONSTRAINT_CHECK               := (SQLITE_CONSTRAINT | (1<<8))
SQLITE_CONSTRAINT_COMMITHOOK          := (SQLITE_CONSTRAINT | (2<<8))
SQLITE_CONSTRAINT_FOREIGNKEY          := (SQLITE_CONSTRAINT | (3<<8))
SQLITE_CONSTRAINT_FUNCTION            := (SQLITE_CONSTRAINT | (4<<8))
SQLITE_CONSTRAINT_NOTNULL             := (SQLITE_CONSTRAINT | (5<<8))
SQLITE_CONSTRAINT_PRIMARYKEY          := (SQLITE_CONSTRAINT | (6<<8))
SQLITE_CONSTRAINT_TRIGGER             := (SQLITE_CONSTRAINT | (7<<8))
SQLITE_CONSTRAINT_UNIQUE              := (SQLITE_CONSTRAINT | (8<<8))
SQLITE_CONSTRAINT_VTAB                := (SQLITE_CONSTRAINT | (9<<8))
SQLITE_CONSTRAINT_ROWID               := (SQLITE_CONSTRAINT |(10<<8))
SQLITE_CONSTRAINT_PINNED              := (SQLITE_CONSTRAINT |(11<<8))
SQLITE_CONSTRAINT_DATATYPE            := (SQLITE_CONSTRAINT |(12<<8))
SQLITE_NOTICE_RECOVER_WAL             := (SQLITE_NOTICE     | (1<<8))
SQLITE_NOTICE_RECOVER_ROLLBACK        := (SQLITE_NOTICE     | (2<<8))
SQLITE_NOTICE_RBU                     := (SQLITE_NOTICE     | (3<<8))
SQLITE_WARNING_AUTOINDEX              := (SQLITE_WARNING    | (1<<8))
SQLITE_AUTH_USER                      := (SQLITE_AUTH       | (1<<8))
SQLITE_OK_LOAD_PERMANENTLY            := (SQLITE_OK         | (1<<8))
SQLITE_OK_SYMLINK                     := (SQLITE_OK         | (2<<8))       ; internal use only
SQLITE_OPEN_READONLY                  := 0x00000001                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_READWRITE                 := 0x00000002                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_CREATE                    := 0x00000004                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_DELETEONCLOSE             := 0x00000008                 ; VFS only
SQLITE_OPEN_EXCLUSIVE                 := 0x00000010                 ; VFS only
SQLITE_OPEN_AUTOPROXY                 := 0x00000020                 ; VFS only
SQLITE_OPEN_URI                       := 0x00000040                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_MEMORY                    := 0x00000080                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_MAIN_DB                   := 0x00000100                 ; VFS only
SQLITE_OPEN_TEMP_DB                   := 0x00000200                 ; VFS only
SQLITE_OPEN_TRANSIENT_DB              := 0x00000400                 ; VFS only
SQLITE_OPEN_MAIN_JOURNAL              := 0x00000800                 ; VFS only
SQLITE_OPEN_TEMP_JOURNAL              := 0x00001000                 ; VFS only
SQLITE_OPEN_SUBJOURNAL                := 0x00002000                 ; VFS only
SQLITE_OPEN_SUPER_JOURNAL             := 0x00004000                 ; VFS only
SQLITE_OPEN_NOMUTEX                   := 0x00008000                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_FULLMUTEX                 := 0x00010000                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_SHAREDCACHE               := 0x00020000                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_PRIVATECACHE              := 0x00040000                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_WAL                       := 0x00080000                 ; VFS only
SQLITE_OPEN_NOFOLLOW                  := 0x01000000                 ; Ok for sqlite3_open_v2()
SQLITE_OPEN_EXRESCODE                 := 0x02000000                 ; Extended result codes
SQLITE_OPEN_MASTER_JOURNAL            := 0x00004000                 ; VFS only
SQLITE_IOCAP_ATOMIC                   := 0x00000001
SQLITE_IOCAP_ATOMIC512                := 0x00000002
SQLITE_IOCAP_ATOMIC1K                 := 0x00000004
SQLITE_IOCAP_ATOMIC2K                 := 0x00000008
SQLITE_IOCAP_ATOMIC4K                 := 0x00000010
SQLITE_IOCAP_ATOMIC8K                 := 0x00000020
SQLITE_IOCAP_ATOMIC16K                := 0x00000040
SQLITE_IOCAP_ATOMIC32K                := 0x00000080
SQLITE_IOCAP_ATOMIC64K                := 0x00000100
SQLITE_IOCAP_SAFE_APPEND              := 0x00000200
SQLITE_IOCAP_SEQUENTIAL               := 0x00000400
SQLITE_IOCAP_UNDELETABLE_WHEN_OPEN    := 0x00000800
SQLITE_IOCAP_POWERSAFE_OVERWRITE      := 0x00001000
SQLITE_IOCAP_IMMUTABLE                := 0x00002000
SQLITE_IOCAP_BATCH_ATOMIC             := 0x00004000
SQLITE_LOCK_NONE                      := 0                          ; xUnlock() only
SQLITE_LOCK_SHARED                    := 1                          ; xLock() or xUnlock()
SQLITE_LOCK_RESERVED                  := 2                          ; xLock() only
SQLITE_LOCK_PENDING                   := 3                          ; xLock() only
SQLITE_LOCK_EXCLUSIVE                 := 4                          ; xLock() only
SQLITE_SYNC_NORMAL                    := 0x00002
SQLITE_SYNC_FULL                      := 0x00003
SQLITE_SYNC_DATAONLY                  := 0x00010
SQLITE_FCNTL_LOCKSTATE                := 1
SQLITE_FCNTL_GET_LOCKPROXYFILE        := 2
SQLITE_FCNTL_SET_LOCKPROXYFILE        := 3
SQLITE_FCNTL_LAST_ERRNO               := 4
SQLITE_FCNTL_SIZE_HINT                := 5
SQLITE_FCNTL_CHUNK_SIZE               := 6
SQLITE_FCNTL_FILE_POINTER             := 7
SQLITE_FCNTL_SYNC_OMITTED             := 8
SQLITE_FCNTL_WIN32_AV_RETRY           := 9
SQLITE_FCNTL_PERSIST_WAL              := 10
SQLITE_FCNTL_OVERWRITE                := 11
SQLITE_FCNTL_VFSNAME                  := 12
SQLITE_FCNTL_POWERSAFE_OVERWRITE      := 13
SQLITE_FCNTL_PRAGMA                   := 14
SQLITE_FCNTL_BUSYHANDLER              := 15
SQLITE_FCNTL_TEMPFILENAME             := 16
SQLITE_FCNTL_MMAP_SIZE                := 18
SQLITE_FCNTL_TRACE                    := 19
SQLITE_FCNTL_HAS_MOVED                := 20
SQLITE_FCNTL_SYNC                     := 21
SQLITE_FCNTL_COMMIT_PHASETWO          := 22
SQLITE_FCNTL_WIN32_SET_HANDLE         := 23
SQLITE_FCNTL_WAL_BLOCK                := 24
SQLITE_FCNTL_ZIPVFS                   := 25
SQLITE_FCNTL_RBU                      := 26
SQLITE_FCNTL_VFS_POINTER              := 27
SQLITE_FCNTL_JOURNAL_POINTER          := 28
SQLITE_FCNTL_WIN32_GET_HANDLE         := 29
SQLITE_FCNTL_PDB                      := 30
SQLITE_FCNTL_BEGIN_ATOMIC_WRITE       := 31
SQLITE_FCNTL_COMMIT_ATOMIC_WRITE      := 32
SQLITE_FCNTL_ROLLBACK_ATOMIC_WRITE    := 33
SQLITE_FCNTL_LOCK_TIMEOUT             := 34
SQLITE_FCNTL_DATA_VERSION             := 35
SQLITE_FCNTL_SIZE_LIMIT               := 36
SQLITE_FCNTL_CKPT_DONE                := 37
SQLITE_FCNTL_RESERVE_BYTES            := 38
SQLITE_FCNTL_CKPT_START               := 39
SQLITE_FCNTL_EXTERNAL_READER          := 40
SQLITE_FCNTL_CKSM_FILE                := 41
SQLITE_FCNTL_RESET_CACHE              := 42
SQLITE_GET_LOCKPROXYFILE              := SQLITE_FCNTL_GET_LOCKPROXYFILE
SQLITE_SET_LOCKPROXYFILE              := SQLITE_FCNTL_SET_LOCKPROXYFILE
SQLITE_LAST_ERRNO                     := SQLITE_FCNTL_LAST_ERRNO
SQLITE_ACCESS_EXISTS                  := 0
SQLITE_ACCESS_READWRITE               := 1                          ; Used by PRAGMA temp_store_directory
SQLITE_ACCESS_READ                    := 2                          ; Unused
SQLITE_SHM_UNLOCK                     := 1
SQLITE_SHM_LOCK                       := 2
SQLITE_SHM_SHARED                     := 4
SQLITE_SHM_EXCLUSIVE                  := 8
SQLITE_SHM_NLOCK                      := 8
SQLITE_CONFIG_SINGLETHREAD            := 1                          ; nil
SQLITE_CONFIG_MULTITHREAD             := 2                          ; nil
SQLITE_CONFIG_SERIALIZED              := 3                          ; nil
SQLITE_CONFIG_MALLOC                  := 4                          ; sqlite3_mem_methods*
SQLITE_CONFIG_GETMALLOC               := 5                          ; sqlite3_mem_methods*
SQLITE_CONFIG_SCRATCH                 := 6                          ; No longer used
SQLITE_CONFIG_PAGECACHE               := 7                          ; void*, int sz, int N
SQLITE_CONFIG_HEAP                    := 8                          ; void*, int nByte, int min
SQLITE_CONFIG_MEMSTATUS               := 9                          ; boolean
SQLITE_CONFIG_MUTEX                   := 10                         ; sqlite3_mutex_methods*
SQLITE_CONFIG_GETMUTEX                := 11                         ; sqlite3_mutex_methods*
SQLITE_CONFIG_LOOKASIDE               := 13                         ; int int
SQLITE_CONFIG_PCACHE                  := 14                         ; no-op
SQLITE_CONFIG_GETPCACHE               := 15                         ; no-op
SQLITE_CONFIG_LOG                     := 16                         ; xFunc, void*
SQLITE_CONFIG_URI                     := 17                         ; int
SQLITE_CONFIG_PCACHE2                 := 18                         ; sqlite3_pcache_methods2*
SQLITE_CONFIG_GETPCACHE2              := 19                         ; sqlite3_pcache_methods2*
SQLITE_CONFIG_COVERING_INDEX_SCAN     := 20                         ; int
SQLITE_CONFIG_SQLLOG                  := 21                         ; xSqllog, void*
SQLITE_CONFIG_MMAP_SIZE               := 22                         ; sqlite3_int64, sqlite3_int64
SQLITE_CONFIG_WIN32_HEAPSIZE          := 23                         ; int nByte
SQLITE_CONFIG_PCACHE_HDRSZ            := 24                         ; int *psz
SQLITE_CONFIG_PMASZ                   := 25                         ; unsigned int szPma
SQLITE_CONFIG_STMTJRNL_SPILL          := 26                         ; int nByte
SQLITE_CONFIG_SMALL_MALLOC            := 27                         ; boolean
SQLITE_CONFIG_SORTERREF_SIZE          := 28                         ; int nByte
SQLITE_CONFIG_MEMDB_MAXSIZE           := 29                         ; sqlite3_int64
SQLITE_DBCONFIG_MAINDBNAME            := 1000                       ; const char*
SQLITE_DBCONFIG_LOOKASIDE             := 1001                       ; void* int int
SQLITE_DBCONFIG_ENABLE_FKEY           := 1002                       ; int int*
SQLITE_DBCONFIG_ENABLE_TRIGGER        := 1003                       ; int int*
SQLITE_DBCONFIG_ENABLE_FTS3_TOKENIZER := 1004                       ; int int*
SQLITE_DBCONFIG_ENABLE_LOAD_EXTENSION := 1005                       ; int int*
SQLITE_DBCONFIG_NO_CKPT_ON_CLOSE      := 1006                       ; int int*
SQLITE_DBCONFIG_ENABLE_QPSG           := 1007                       ; int int*
SQLITE_DBCONFIG_TRIGGER_EQP           := 1008                       ; int int*
SQLITE_DBCONFIG_RESET_DATABASE        := 1009                       ; int int*
SQLITE_DBCONFIG_DEFENSIVE             := 1010                       ; int int*
SQLITE_DBCONFIG_WRITABLE_SCHEMA       := 1011                       ; int int*
SQLITE_DBCONFIG_LEGACY_ALTER_TABLE    := 1012                       ; int int*
SQLITE_DBCONFIG_DQS_DML               := 1013                       ; int int*
SQLITE_DBCONFIG_DQS_DDL               := 1014                       ; int int*
SQLITE_DBCONFIG_ENABLE_VIEW           := 1015                       ; int int*
SQLITE_DBCONFIG_LEGACY_FILE_FORMAT    := 1016                       ; int int*
SQLITE_DBCONFIG_TRUSTED_SCHEMA        := 1017                       ; int int*
SQLITE_DBCONFIG_STMT_SCANSTATUS       := 1018                       ; int int*
SQLITE_DBCONFIG_REVERSE_SCANORDER     := 1019                       ; int int*
SQLITE_DBCONFIG_MAX                   := 1019                       ; Largest DBCONFIG
SQLITE_DENY                           := 1                          ; Abort the SQL statement with an error
SQLITE_IGNORE                         := 2                          ; Don't allow access, but don't generate an error
SQLITE_CREATE_INDEX                   := 1                          ; Index Name      Table Name     
SQLITE_CREATE_TABLE                   := 2                          ; Table Name      NULL           
SQLITE_CREATE_TEMP_INDEX              := 3                          ; Index Name      Table Name     
SQLITE_CREATE_TEMP_TABLE              := 4                          ; Table Name      NULL           
SQLITE_CREATE_TEMP_TRIGGER            := 5                          ; Trigger Name    Table Name     
SQLITE_CREATE_TEMP_VIEW               := 6                          ; View Name       NULL           
SQLITE_CREATE_TRIGGER                 := 7                          ; Trigger Name    Table Name     
SQLITE_CREATE_VIEW                    := 8                          ; View Name       NULL           
SQLITE_DELETE                         := 9                          ; Table Name      NULL           
SQLITE_DROP_INDEX                     := 10                         ; Index Name      Table Name     
SQLITE_DROP_TABLE                     := 11                         ; Table Name      NULL           
SQLITE_DROP_TEMP_INDEX                := 12                         ; Index Name      Table Name     
SQLITE_DROP_TEMP_TABLE                := 13                         ; Table Name      NULL           
SQLITE_DROP_TEMP_TRIGGER              := 14                         ; Trigger Name    Table Name     
SQLITE_DROP_TEMP_VIEW                 := 15                         ; View Name       NULL           
SQLITE_DROP_TRIGGER                   := 16                         ; Trigger Name    Table Name     
SQLITE_DROP_VIEW                      := 17                         ; View Name       NULL           
SQLITE_INSERT                         := 18                         ; Table Name      NULL           
SQLITE_PRAGMA                         := 19                         ; Pragma Name     1st arg or NULL
SQLITE_READ                           := 20                         ; Table Name      Column Name    
SQLITE_SELECT                         := 21                         ; NULL            NULL           
SQLITE_TRANSACTION                    := 22                         ; Operation       NULL           
SQLITE_UPDATE                         := 23                         ; Table Name      Column Name    
SQLITE_ATTACH                         := 24                         ; Filename        NULL           
SQLITE_DETACH                         := 25                         ; Database Name   NULL           
SQLITE_ALTER_TABLE                    := 26                         ; Database Name   Table Name     
SQLITE_REINDEX                        := 27                         ; Index Name      NULL           
SQLITE_ANALYZE                        := 28                         ; Table Name      NULL           
SQLITE_CREATE_VTABLE                  := 29                         ; Table Name      Module Name    
SQLITE_DROP_VTABLE                    := 30                         ; Table Name      Module Name    
SQLITE_FUNCTION                       := 31                         ; NULL            Function Name  
SQLITE_SAVEPOINT                      := 32                         ; Operation       Savepoint Name 
SQLITE_COPY                           := 0                          ; No longer used
SQLITE_RECURSIVE                      := 33                         ; NULL            NULL           
SQLITE_TRACE_STMT                     := 0x01
SQLITE_TRACE_PROFILE                  := 0x02
SQLITE_TRACE_ROW                      := 0x04
SQLITE_TRACE_CLOSE                    := 0x08
SQLITE_LIMIT_LENGTH                   := 0
SQLITE_LIMIT_SQL_LENGTH               := 1
SQLITE_LIMIT_COLUMN                   := 2
SQLITE_LIMIT_EXPR_DEPTH               := 3
SQLITE_LIMIT_COMPOUND_SELECT          := 4
SQLITE_LIMIT_VDBE_OP                  := 5
SQLITE_LIMIT_FUNCTION_ARG             := 6
SQLITE_LIMIT_ATTACHED                 := 7
SQLITE_LIMIT_LIKE_PATTERN_LENGTH      := 8
SQLITE_LIMIT_VARIABLE_NUMBER          := 9
SQLITE_LIMIT_TRIGGER_DEPTH            := 10
SQLITE_LIMIT_WORKER_THREADS           := 11
SQLITE_PREPARE_PERSISTENT             := 0x01
SQLITE_PREPARE_NORMALIZE              := 0x02
SQLITE_PREPARE_NO_VTAB                := 0x04
SQLITE_INTEGER                        := 1
SQLITE_FLOAT                          := 2
SQLITE_BLOB                           := 4
SQLITE_NULL                           := 5
SQLITE3_TEXT                          := 3
SQLITE_UTF8                           := 1                          ; IMP: R-37514-35566
SQLITE_UTF16LE                        := 2                          ; IMP: R-03371-37637
SQLITE_UTF16BE                        := 3                          ; IMP: R-51971-34154
SQLITE_UTF16                          := 4                          ; Use native byte order
SQLITE_ANY                            := 5                          ; Deprecated
SQLITE_UTF16_ALIGNED                  := 8                          ; sqlite3_create_collation only
SQLITE_DETERMINISTIC                  := 0x000000800
SQLITE_DIRECTONLY                     := 0x000080000
SQLITE_SUBTYPE                        := 0x000100000
SQLITE_INNOCUOUS                      := 0x000200000
; SQLITE_STATIC                         := ((sqlite3_destructor_type)0)
; SQLITE_TRANSIENT                      := ((sqlite3_destructor_type)-1)
SQLITE_WIN32_DATA_DIRECTORY_TYPE      := 1
SQLITE_WIN32_TEMP_DIRECTORY_TYPE      := 2
SQLITE_TXN_NONE                       := 0
SQLITE_TXN_READ                       := 1
SQLITE_TXN_WRITE                      := 2
SQLITE_INDEX_SCAN_UNIQUE              := 1                          ; Scan visits at most 1 row
SQLITE_INDEX_CONSTRAINT_EQ            := 2
SQLITE_INDEX_CONSTRAINT_GT            := 4
SQLITE_INDEX_CONSTRAINT_LE            := 8
SQLITE_INDEX_CONSTRAINT_LT            := 16
SQLITE_INDEX_CONSTRAINT_GE            := 32
SQLITE_INDEX_CONSTRAINT_MATCH         := 64
SQLITE_INDEX_CONSTRAINT_LIKE          := 65
SQLITE_INDEX_CONSTRAINT_GLOB          := 66
SQLITE_INDEX_CONSTRAINT_REGEXP        := 67
SQLITE_INDEX_CONSTRAINT_NE            := 68
SQLITE_INDEX_CONSTRAINT_ISNOT         := 69
SQLITE_INDEX_CONSTRAINT_ISNOTNULL     := 70
SQLITE_INDEX_CONSTRAINT_ISNULL        := 71
SQLITE_INDEX_CONSTRAINT_IS            := 72
SQLITE_INDEX_CONSTRAINT_LIMIT         := 73
SQLITE_INDEX_CONSTRAINT_OFFSET        := 74
SQLITE_INDEX_CONSTRAINT_FUNCTION      := 150
SQLITE_MUTEX_FAST                     := 0
SQLITE_MUTEX_RECURSIVE                := 1
SQLITE_MUTEX_STATIC_MAIN              := 2
SQLITE_MUTEX_STATIC_MEM               := 3                          ; sqlite3_malloc()
SQLITE_MUTEX_STATIC_MEM2              := 4                          ; NOT USED
SQLITE_MUTEX_STATIC_OPEN              := 4                          ; sqlite3BtreeOpen()
SQLITE_MUTEX_STATIC_PRNG              := 5                          ; sqlite3_randomness()
SQLITE_MUTEX_STATIC_LRU               := 6                          ; lru page list
SQLITE_MUTEX_STATIC_LRU2              := 7                          ; NOT USED
SQLITE_MUTEX_STATIC_PMEM              := 7                          ; sqlite3PageMalloc()
SQLITE_MUTEX_STATIC_APP1              := 8                          ; For use by application
SQLITE_MUTEX_STATIC_APP2              := 9                          ; For use by application
SQLITE_MUTEX_STATIC_APP3              := 10                         ; For use by application
SQLITE_MUTEX_STATIC_VFS1              := 11                         ; For use by built-in VFS
SQLITE_MUTEX_STATIC_VFS2              := 12                         ; For use by extension VFS
SQLITE_MUTEX_STATIC_VFS3              := 13                         ; For use by application VFS
SQLITE_MUTEX_STATIC_MASTER            := 2
SQLITE_TESTCTRL_FIRST                 := 5
SQLITE_TESTCTRL_PRNG_SAVE             := 5
SQLITE_TESTCTRL_PRNG_RESTORE          := 6
SQLITE_TESTCTRL_PRNG_RESET            := 7                          ; NOT USED
SQLITE_TESTCTRL_BITVEC_TEST           := 8
SQLITE_TESTCTRL_FAULT_INSTALL         := 9
SQLITE_TESTCTRL_BENIGN_MALLOC_HOOKS   := 10
SQLITE_TESTCTRL_PENDING_BYTE          := 11
SQLITE_TESTCTRL_ASSERT                := 12
SQLITE_TESTCTRL_ALWAYS                := 13
SQLITE_TESTCTRL_RESERVE               := 14                         ; NOT USED
SQLITE_TESTCTRL_OPTIMIZATIONS         := 15
SQLITE_TESTCTRL_ISKEYWORD             := 16                         ; NOT USED
SQLITE_TESTCTRL_SCRATCHMALLOC         := 17                         ; NOT USED
SQLITE_TESTCTRL_INTERNAL_FUNCTIONS    := 17
SQLITE_TESTCTRL_LOCALTIME_FAULT       := 18
SQLITE_TESTCTRL_EXPLAIN_STMT          := 19                         ; NOT USED
SQLITE_TESTCTRL_ONCE_RESET_THRESHOLD  := 19
SQLITE_TESTCTRL_NEVER_CORRUPT         := 20
SQLITE_TESTCTRL_VDBE_COVERAGE         := 21
SQLITE_TESTCTRL_BYTEORDER             := 22
SQLITE_TESTCTRL_ISINIT                := 23
SQLITE_TESTCTRL_SORTER_MMAP           := 24
SQLITE_TESTCTRL_IMPOSTER              := 25
SQLITE_TESTCTRL_PARSER_COVERAGE       := 26
SQLITE_TESTCTRL_RESULT_INTREAL        := 27
SQLITE_TESTCTRL_PRNG_SEED             := 28
SQLITE_TESTCTRL_EXTRA_SCHEMA_CHECKS   := 29
SQLITE_TESTCTRL_SEEK_COUNT            := 30
SQLITE_TESTCTRL_TRACEFLAGS            := 31
SQLITE_TESTCTRL_TUNE                  := 32
SQLITE_TESTCTRL_LOGEST                := 33
SQLITE_TESTCTRL_USELONGDOUBLE         := 34
SQLITE_TESTCTRL_LAST                  := 34                         ; Largest TESTCTRL
SQLITE_STATUS_MEMORY_USED             := 0
SQLITE_STATUS_PAGECACHE_USED          := 1
SQLITE_STATUS_PAGECACHE_OVERFLOW      := 2
SQLITE_STATUS_SCRATCH_USED            := 3                          ; NOT USED
SQLITE_STATUS_SCRATCH_OVERFLOW        := 4                          ; NOT USED
SQLITE_STATUS_MALLOC_SIZE             := 5
SQLITE_STATUS_PARSER_STACK            := 6
SQLITE_STATUS_PAGECACHE_SIZE          := 7
SQLITE_STATUS_SCRATCH_SIZE            := 8                          ; NOT USED
SQLITE_STATUS_MALLOC_COUNT            := 9
SQLITE_DBSTATUS_LOOKASIDE_USED        := 0
SQLITE_DBSTATUS_CACHE_USED            := 1
SQLITE_DBSTATUS_SCHEMA_USED           := 2
SQLITE_DBSTATUS_STMT_USED             := 3
SQLITE_DBSTATUS_LOOKASIDE_HIT         := 4
SQLITE_DBSTATUS_LOOKASIDE_MISS_SIZE   := 5
SQLITE_DBSTATUS_LOOKASIDE_MISS_FULL   := 6
SQLITE_DBSTATUS_CACHE_HIT             := 7
SQLITE_DBSTATUS_CACHE_MISS            := 8
SQLITE_DBSTATUS_CACHE_WRITE           := 9
SQLITE_DBSTATUS_DEFERRED_FKS          := 10
SQLITE_DBSTATUS_CACHE_USED_SHARED     := 11
SQLITE_DBSTATUS_CACHE_SPILL           := 12
SQLITE_DBSTATUS_MAX                   := 12                         ; Largest defined DBSTATUS
SQLITE_STMTSTATUS_FULLSCAN_STEP       := 1
SQLITE_STMTSTATUS_SORT                := 2
SQLITE_STMTSTATUS_AUTOINDEX           := 3
SQLITE_STMTSTATUS_VM_STEP             := 4
SQLITE_STMTSTATUS_REPREPARE           := 5
SQLITE_STMTSTATUS_RUN                 := 6
SQLITE_STMTSTATUS_FILTER_MISS         := 7
SQLITE_STMTSTATUS_FILTER_HIT          := 8
SQLITE_STMTSTATUS_MEMUSED             := 99
SQLITE_CHECKPOINT_PASSIVE             := 0                          ; Do as much as possible w/o blocking
SQLITE_CHECKPOINT_FULL                := 1                          ; Wait for writers, then checkpoint
SQLITE_CHECKPOINT_RESTART             := 2                          ; Like FULL but wait for readers
SQLITE_CHECKPOINT_TRUNCATE            := 3                          ; Like RESTART but also truncate WAL
SQLITE_VTAB_CONSTRAINT_SUPPORT        := 1
SQLITE_VTAB_INNOCUOUS                 := 2
SQLITE_VTAB_DIRECTONLY                := 3
SQLITE_VTAB_USES_ALL_SCHEMAS          := 4
SQLITE_ROLLBACK                       := 1
SQLITE_IGNORE                         := 2                          ; Also used by sqlite3_authorizer() callback
SQLITE_FAIL                           := 3
SQLITE_ABORT                          := 4                          ; Also an error code */
SQLITE_REPLACE                        := 5
SQLITE_SCANSTAT_NLOOP                 := 0
SQLITE_SCANSTAT_NVISIT                := 1
SQLITE_SCANSTAT_EST                   := 2
SQLITE_SCANSTAT_NAME                  := 3
SQLITE_SCANSTAT_EXPLAIN               := 4
SQLITE_SCANSTAT_SELECTID              := 5
SQLITE_SCANSTAT_PARENTID              := 6
SQLITE_SCANSTAT_NCYCLE                := 7
SQLITE_SCANSTAT_COMPLEX               := 0x0001
SQLITE_SERIALIZE_NOCOPY               := 0x001                      ; Do no memory allocations
SQLITE_DESERIALIZE_FREEONCLOSE        := 1                          ; Call sqlite3_free() on close
SQLITE_DESERIALIZE_RESIZEABLE         := 2                          ; Resize using sqlite3_realloc64()
SQLITE_DESERIALIZE_READONLY           := 4                          ; Database is read-only
_SQLITE3RTREE_H_                      := 
NOT_WITHIN                            := 0                          ; Object completely outside of query region
PARTLY_WITHIN                         := 1                          ; Object partially overlaps query region
FULLY_WITHIN                          := 2                          ; Object fully contained within query region
__SQLITESESSION_H_                    := 1
SQLITE_SESSION_OBJCONFIG_SIZE         := 1
SQLITE_SESSION_OBJCONFIG_ROWID        := 2
SQLITE_CHANGESETSTART_INVERT          := 0x0002
SQLITE_CHANGESETAPPLY_NOSAVEPOINT     := 0x0001
SQLITE_CHANGESETAPPLY_INVERT          := 0x0002
SQLITE_CHANGESETAPPLY_IGNORENOOP      := 0x0004
SQLITE_CHANGESET_DATA                 := 1
SQLITE_CHANGESET_NOTFOUND             := 2
SQLITE_CHANGESET_CONFLICT             := 3
SQLITE_CHANGESET_CONSTRAINT           := 4
SQLITE_CHANGESET_FOREIGN_KEY          := 5
SQLITE_CHANGESET_OMIT                 := 0
SQLITE_CHANGESET_REPLACE              := 1
SQLITE_CHANGESET_ABORT                := 2
SQLITE_SESSION_CONFIG_STRMSIZE        := 1
FTS5_TOKENIZE_QUERY                   := 0x0001
FTS5_TOKENIZE_PREFIX                  := 0x0002
FTS5_TOKENIZE_DOCUMENT                := 0x0004
FTS5_TOKENIZE_AUX                     := 0x0008
FTS5_TOKEN_COLOCATED                  := 0x0001                     ; Same position as prev. token